[general]
destination = "$HOME/.config/hypr/monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_AC"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_AC"

[profiles.docked]
config_file = "/home/god/.flakes/home/modules/assets/.config/hyprdynamicmonitors/hyprconfigs/docked.go.tmpl"
config_file_type = "template"


